// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Applications  string
	Endpoints     string
	Environments  string
	Members       string
	Organizations string
}{
	Applications:  "applications",
	Endpoints:     "endpoints",
	Environments:  "environments",
	Members:       "members",
	Organizations: "organizations",
}
