version: '3.9'

services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.9.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./misc/tools/reflex
    stop_grace_period: 1s
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
