services:
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.9.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  app:
    build: ./misc/tools/reflex
    stop_grace_period: 1s
    environment:
      APP_NAME: backend
    env_file:
      - ./.env
      - ./.env.secrets
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
      - ${GOCACHE:-/tmp/go-cache}:/root/.cache/go-build
      - ${GOMODCACHE:-/tmp/go-mod-cache}:/go/pkg/mod

  emulators:
    build: ./misc/tools/reflex
    stop_grace_period: 1s
    restart: always
    env_file:
      ./.env
    environment:
      APP_NAME: emulators
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - .:/usr/app
