version: 3

tasks:
  server:
    dir: ./server
    cmds:
      - docker compose up -d

  web:
    dir: ./web
    cmds:
      - npm run dev

  docker:build:
    cmds:
      - docker build -t subscribed .
  docker:run:
    cmds:
      - docker run -p 8090:8090 --rm --env-file ./.env.docker subscribed
