name: ci.web
on:
  workflow_call:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          # https://github.com/actions/setup-node#caching-global-packages-data
          cache-dependency-path: "web/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Codegen API Client
        run: npm run openapi

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Lint (css)
        run: npm run lint:css

      - name: Code fmt
        run: npm run fmt

      # TODO: setup Vite w/ Jest
      # https://dev.to/michaeljota/how-to-add-jest-into-your-vite-project-with-ts-5d21
      # - name: Test
      #   run: npm run test:unit
