name: main
on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  tag:
    uses: ./.github/workflows/tag.yml
    needs: ci
    secrets:
      PAT: ${{ secrets.PAT }}
