name: pr.server
on:
  push:
    paths-ignore:
      - "*.md"
    paths:
      - "server/**"
      - ".github/workflows/*.server.yml"
    branches-ignore:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.server.yml
