name: pr.web
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "*.md"
    paths:
      - "web/**"
      - ".github/workflows/*.web.yml"

jobs:
  ci:
    uses: ./.github/workflows/ci.web.yml
